<html>
<head>
    <title>Moja knjiga 1</title>



    <?php $this->assets->outputCss(); ?>
    <?php  $this->assets->outputJs(); ?>



</head>
<body>
<div id="wrapper">

    <!-- Main -->

    <div id="main">

        <div class="inner">
            <header id="header">
                <a href="index.phtml" class="logo"><strong>Moja knjiga</strong>  HEXIS</a>
                <ul class="icons">
                    <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                    <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                    <li><a href="#" class="icon fa-snapchat-ghost"><span class="label">Snapchat</span></a></li>
                    <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                    <li><a href="#" class="icon fa-medium"><span class="label">Medium</span></a></li>
                </ul>
            </header>


            <?php echo $this->flashSession->output(); ?>
            <?php echo $this->getContent(); ?>

        </div>
    </div>
    <!-- Sidebar -->
    <div id="sidebar">
        <div class="inner">


            <!-- Menu -->
            <nav id="menu">
                <header class="major">
                    <h2>Menu</h2>
                </header>
                <?php
                //error_reporting(E_ALL);
                //ini_set('display_errors', 'Off');
                if ($this->session->get("user_id") <> null) { ?>

                    <ul>
                        <li> <?php echo $this->tag->linkTo("index", "Home"); ?></li>
                        <li><?php echo $this->tag->linkTo("invite", "Pozovi korisnika"); ?></li>

                        <li>
                            <span class="opener">Knjige</span>
                            <ul>
                                <li><?php echo $this->tag->linkTo("mybooks", "Moje knjige"); ?></li>
                                <li><?php echo $this->tag->linkTo("groups", "Knjige grupa"); ?></li>
                                <li><?php echo $this->tag->linkTo("search", "Pretraži knjige"); ?></li>
                                <li><?php echo $this->tag->linkTo("addbooks", "Dodaj knjigu"); ?></li>

                            </ul>


                        </li>
                        <li><?php echo $this->tag->linkTo("User/logout", "Odjavi se"); ?></li>

                    </ul>
                    <?php
                         } else {
                         ?>
                    <ul>
                        <li> <?php echo $this->tag->linkTo("index", "Home"); ?></li>
                        <li> <?php echo $this->tag->linkTo("login", "Prijavi se"); ?></li>
                        <li> <?php echo $this->tag->linkTo("signup", "Registriraj se"); ?></li>


                    </ul>
                    <?php
                }

                ?>
            </nav>

            <!-- Section -->


            <!-- Footer -->
            <footer id="footer">
                <p class="copyright">&copy; HEXIS </p>
            </footer>

        </div>
    </div>
</body>
</html>
